name: src-deploy

on:
  push:
    tags:
      - 'deploy-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: build
        run: npm run build

      - name: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to s3
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            out s3://src-landing \
            --delete
